language: python
python:
  - "2.7"
env:
  - TOX_ENV=27gevent
  - TOX_ENV=pypygevent
# Not working yet, for some reason.
#  - TOX_ENV=33gevent
install:
  - "pip install tox --download-cache $HOME/.pip-cache"
  - "pip install coveralls --download-cache $HOME/.pip-cache"
before_script:
  - "coverage erase"
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
cache:
  directories:
    - .tox
    - $HOME/.pip-cache/
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: chuim
  password:
    secure: XEB8GFOxRWVhMX2O/at9DF3Y3xQA71+ZJL5zF/KCyY5aKA7WnerwmRT/4s6HIpC1MG8H8f2sexFywSsOOHSa8TybHtZNDSQEMN2G7Xcynv3u+WEICGDUfanRL+17Q7YjvU7WzdddcTzSmn9DVrv+YqfN+3p6QzWSXhNQWqcDsIk=
  on:
    branch: production
