language: python
python:
  - "2.7"
env:
#  - TOX_ENV=27gevent
#  - TOX_ENV=pypygevent
#  - TOX_ENV=33gevent
  - TOX_ENV=27slp
before_install:
  - wget http://www.robg3d.com/downloads/stackless-2.7.6_amd64.zip
  - unzip stackless-2.7.6_amd64.zip
#install:
#  - "pip install tox --download-cache $HOME/.pip-cache"
#  - "pip install coveralls --download-cache $HOME/.pip-cache"
script:
  - $HOME/stackless-2.7.6/bin/python --version
#  - tox -e $TOX_ENV
#after_failure:
#  - "cat /home/travis/build/rgalanakis/goless/.tox/33gevent/log/33gevent-*.log"
#  - "cat /home/travis/.pip/pip.log"
#after_success:
#  - coveralls
cache:
  directories:
    - .tox
    - $HOME/.pip-cache/
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: chuim
  password:
    secure: NpFysWBjDlQh4i0EurrA4u4YVAWwfpouopvu+WePYGdae1ebaYtIgXEHLW5yJrNJVSNhG7XkDPXuKUUW+5aM7sAZKQm8gfUN1MCBT6Idpnqq7skQtbmkMOZ06yvJrBhHwL4mZoMJ+ikR0DPqMqgQJuq2eiXNN6mvIGaQF+eJwWY=
  on:
    branch: production
