language: python
matrix:
  include:
    - python: 2.6
      env:
      - TOX_ENV=26gevent
    - python: 2.7
      env:
      - TOX_ENV=27gevent
    - python: 3.3
      env:
      - TOX_ENV=33gevent
    - python: 3.4
      env:
      - TOX_ENV=34gevent
    - python: 3.5
      env:
      - TOX_ENV=35gevent
    - python: 3.6
      env:
      - TOX_ENV=36gevent
    - python: pypy
      env:
      - TOX_ENV=pypy2gevent
    - python: pypy3
      env:
      - TOX_ENV=pypy3gevent
    - python: 2.7
      env:
      - TOX_ENV=27slptravis
before_install:
  - |
    set -e
    if [[ $TOX_ENV == pypy* ]]; then
        # Travis pypy versions are super old, so download manually.
        if [[ $TOX_ENV == pypy2* ]]; then
            PYTHON_NAME="pypy"
            DOWNLOAD_URL="https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.8.0-linux64.tar.bz2"
        elif [[ $TOX_ENV == pypy3* ]]; then
            PYTHON_NAME="pypy3"
            DOWNLOAD_URL="https://bitbucket.org/pypy/pypy/downloads/pypy3-v5.8.0-linux64.tar.bz2"
        fi

        PYTHON_DIR="~/cache/${PYTHON_NAME}"
        if [ ! -d ${PYTHON_DIR} ] ; then
            mkdir -p ${PYTHON_DIR}
            wget -qO- ${DOWNLOAD_URL} | tar jxf - --strip-components=1 -C ${PYTHON_DIR}
        fi
        export PATH=${PYTHON_DIR}/bin:${PATH}
    fi
    if [[ $TOX_ENV = 27slptravis ]] && [ ! -d ~/cache/stackless-2.7.6 ]; then
        wget http://www.robg3d.com/downloads/stackless-2.7.6_amd64.zip
        unzip stackless-2.7.6_amd64.zip -d ~/cache/
    fi
    set +e
install:
  - "pip install tox coveralls"
script:
  - tox -e $TOX_ENV
#after_failure:
#  - "cat /home/travis/build/rgalanakis/goless/.tox/33gevent/log/33gevent-*.log"
#  - "cat /home/travis/.pip/pip.log"
after_success:
  - coveralls
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
    - $HOME/cache
# blacklist
branches:
  except:
    - /^experimental-.*$/
